In [1]:
import numpy as np
import pandas as pd

In [3]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

movies=pd.read_csv('movies.csv',index_col=0)
directors=pd.read_csv('directors.csv')

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: F:\DSML_2026\Python_libraries\Business_case_study\movies.csv

  0%|          | 0.00/112k [00:00<?, ?B/s]
100%|##########| 112k/112k [00:00<00:00, 1.92MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: F:\DSML_2026\Python_libraries\Business_case_study\directors.csv

  0%|          | 0.00/65.4k [00:00<?, ?B/s]
100%|##########| 65.4k/65.4k [00:00<00:00, 3.68MB/s]

In [4]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [7]:
directors.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [8]:
directors.drop(0,axis=1)

KeyError: '[0] not found in axis'

In [9]:
directors.drop('Unnamed: 0',axis=1)

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

# Q1 - How many years of data is given to you in the movies dataset?

In [15]:
movies['year'].max()-movies['year'].min()

np.int64(40)

In [16]:
movies['year'].min()

np.int64(1976)

In [17]:
movies['year'].nunique() #wrong answer

41

# Q2 - Display the ReleaseDate in the Day-Month-Year format

In [18]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [19]:
movies['day']+'-'+movies['month']+'-'+movies['year']

TypeError: can only concatenate str (not "int") to str

In [20]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1465 entries, 0 to 4768
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1465 non-null   int64
 1   budget        1465 non-null   int64
 2   popularity    1465 non-null   int64
 3   revenue       1465 non-null   int64
 4   title         1465 non-null   object
 5   vote_average  1465 non-null   float64
 6   vote_count    1465 non-null   int64
 7   director_id   1465 non-null   int64
 8   year          1465 non-null   int64
 9   month         1465 non-null   object
 10  day           1465 non-null   object
dtypes: float64(1), int64(7), object(3)
memory usage: 137.3+ KB

In [22]:
movies['day']+'-'+movies['month']+'-'+movies['year'].astype('str')

0       Thursday-Dec-2009
1       Saturday-May-2007
2         Monday-Oct-2015
3         Monday-Jul-2012
5        Tuesday-May-2007
              ...
4736      Monday-May-1978
4743     Tuesday-Sep-1994
4748      Friday-Aug-2009
4749      Friday-Jul-1990
4768      Friday-Sep-1992
Length: 1465, dtype: object

# Q3 - What is the % of male directors in the given data?

In [23]:
directors.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [24]:
directors.groupby('gender')['gender'].count()

gender
Female     150
Male      1574
Name: gender, dtype: int64

In [25]:
total=directors.groupby('gender')['gender'].count()[0]+directors.groupby('gender')['gender'].count()[1]

C:\Users\Aadarsh kumar\AppData\Local\Temp\ipykernel_16472\967954354.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  total=directors.groupby('gender')['gender'].count()[0]+directors.groupby('gender')['gender'].count()[1]
C:\Users\Aadarsh kumar\AppData\Local\Temp\ipykernel_16472\967954354.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  total=directors.groupby('gender')['gender'].count()[0]+directors.groupby('gender')['gender'].count()[1]

In [26]:
total

np.int64(1724)

In [27]:
directors.groupby('gender')['gender'].count()[1]/total*100

C:\Users\Aadarsh kumar\AppData\Local\Temp\ipykernel_16472\1190245093.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  directors.groupby('gender')['gender'].count()[1]/total*100

np.float64(91.29930394431554)

In [28]:
directors.groupby('gender')['gender'].count()[0]/total*100

C:\Users\Aadarsh kumar\AppData\Local\Temp\ipykernel_16472\2586773171.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  directors.groupby('gender')['gender'].count()[0]/total*100

np.float64(8.700696055684455)

In [31]:
directors['gender'].value_counts()

gender
Male      1574
Female     150
Name: count, dtype: int64

In [33]:
directors['gender'].value_counts(normalize=True)*100

gender
Male      91.299304
Female     8.700696
Name: proportion, dtype: float64

In [34]:
directors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2349 entries, 0 to 2348
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     2349 non-null   int64
 1   director_name  2349 non-null   object
 2   id             2349 non-null   int64
 3   gender         1724 non-null   object
dtypes: int64(2), object(2)
memory usage: 73.5+ KB

# Q4 - How many different movies have been directed in the year 2010?

In [35]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [39]:
Movies_2010=movies[movies['year']==2010]

In [41]:
Movies_2010

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
21,43618,200000000,37,310669540,Robin Hood,6.2,1398,4779,2010,May,Wednesday
32,43629,200000000,78,1025491110,Alice in Wonderland,6.4,4645,4785,2010,Mar,Wednesday
50,43647,150000000,62,335154643,Prince of Persia: The Sands of Time,6.2,2317,4797,2010,May,Wednesday
79,43676,200000000,77,623933331,Iron Man 2,6.6,6849,4808,2010,Apr,Wednesday
96,43693,160000000,167,825532764,Inception,8.1,13752,4765,2010,Jul,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...
3272,46869,8000000,7,18124262,Another Year,7.0,97,5709,2010,Nov,Friday
3733,47333,4000000,10,0,Survival of the Dead,4.6,116,4991,2010,May,Thursday
3924,47524,3000000,5,0,Please Give,6.0,57,6204,2010,Jan,Friday
4216,47821,1500000,58,97009150,Insidious,6.8,1737,4794,2010,Sep,Monday
4648,48274,0,5,2611555,Three,6.3,31,4936,2010,Dec,Thursday

In [42]:
len(Movies_2010)

63

In [43]:
Movies_2010['id'].nunique()

63

# Q5 How many different directors have directed a movie since 2010 (inclusive)?

In [44]:
DD_Movies_2010=movies[movies['year']>=2010]

In [45]:
DD_Movies_2010

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
9,43606,250000000,155,873260194,Batman v Superman: Dawn of Justice,5.7,7004,4771,2016,Mar,Wednesday
13,43610,255000000,49,89289910,The Lone Ranger,5.9,2311,4763,2013,Jul,Wednesday
14,43611,225000000,99,662845518,Man of Steel,6.5,6359,4771,2013,Jun,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...
4455,48068,0,5,0,Kevin Hart: Laugh at My Pain,7.7,43,4894,2011,Sep,Friday
4532,48146,0,10,316472,Good Kill,5.9,208,5226,2015,Apr,Thursday
4540,48155,0,0,0,Alleluia! The Devil's Carnival,6.0,2,6056,2016,Mar,Tuesday
4621,48244,250000,6,56825,The Canyons,4.1,75,5970,2013,Jul,Monday
4648,48274,0,5,2611555,Three,6.3,31,4936,2010,Dec,Thursday

In [46]:
DD_Movies_2010['director_id'].nunique()

163

In [47]:
id_we_want=DD_Movies_2010['director_id'].unique()

In [48]:
id_we_want

array([4764, 4765, 4771, 4763, 4775, 4776, 4777, 4779, 4782, 4785, 4788,
       4767, 4791, 4794, 4773, 4772, 4797, 4798, 4802, 4805, 4809, 4811,
       4813, 4808, 4803, 4831, 4832, 4838, 4845, 4847, 4849, 4854, 4857,
       4858, 4865, 4868, 4872, 4799, 4874, 4880, 4881, 4842, 4886, 4888,
       4873, 4867, 4876, 4900, 4913, 4924, 4925, 4927, 4930, 4936, 4786,
       4846, 4945, 4948, 4885, 4923, 4960, 4829, 4974, 4993, 4964, 4917,
       5035, 5034, 5059, 4839, 4998, 4918, 4958, 5067, 5088, 4793, 5097,
       5105, 4909, 5123, 5147, 5087, 4955, 5053, 5056, 5202, 5226, 5231,
       5235, 5096, 5039, 5293, 4949, 5196, 4978, 4894, 5310, 5303, 5307,
       5323, 5115, 4989, 5203, 5363, 5367, 5369, 5135, 5047, 4810, 5024,
       5093, 4804, 5191, 5125, 5228, 5457, 4995, 4863, 5033, 5249, 5405,
       5519, 5116, 5549, 5005, 5375, 5554, 5262, 5111, 5489, 5140, 4774,
       5207, 5451, 5465, 5338, 4814, 5157, 5229, 5182, 4859, 5222, 5101,
       5450, 4926, 4904, 5283, 5709, 4893, 5894, 5082, 4780, 6204, 5179,
       5535, 5162, 5008, 5951, 5970, 4991, 5148, 5195, 6056])

# Q 6 What are the names of those directors?

In [49]:
directors.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [50]:
director_name_More_2010=directors[directors['id'].isin(id_we_want)]['director_name']

In [51]:
director_name_More_2010

1            Gore Verbinski
2                Sam Mendes
3         Christopher Nolan
5                 Sam Raimi
9               Zack Snyder
               ...
1132          Brad Anderson
1189         Michael Polish
1208          Paul Schrader
1294    Darren Lynn Bousman
1442      Nicole Holofcener
Name: director_name, Length: 163, dtype: object

# Q7 - Display the name of the director who directed the Spider-Man 3 movie.

In [53]:
directors.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [54]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [55]:
SPM3=movies[movies['title']=='Spider-Man 3']

In [56]:
SPM3

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [61]:
SPM3_Did=movies[movies['title']=='Spider-Man 3']['director_id']

In [62]:
SPM3_Did

5    4767
Name: director_id, dtype: int64

In [68]:
SPM3_Did_Val=movies[movies['title']=='Spider-Man 3']['director_id'][5]

In [69]:
movies[movies['title'] == "Spider-Man 3"]['director_id'].reset_index(drop=True)

0    4767
Name: director_id, dtype: int64

In [73]:
d_id = movies[movies['title'] == "Spider-Man 3"]['director_id'].reset_index(drop=True)[0] # if you don't want to give hardcoded value as 5

In [74]:
D_name=directors[directors['id']==d_id]['director_name']

In [75]:
D_name

5    Sam Raimi
Name: director_name, dtype: object

#### Now if i want to solve this by using merge (join)

In [76]:
directors

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [77]:
movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [78]:
data=movies.merge(directors,how='inner',left_on='director_id',right_on='id')

In [79]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,Unnamed: 0,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,0,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,1,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,2,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,3,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,5,Sam Raimi,4767,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday,47,Martin Scorsese,4809,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday,607,Kevin Smith,5369,Male
1462,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday,386,Uwe Boll,5148,Male
1463,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday,773,Richard Linklater,5535,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday,335,Robert Rodriguez,5097,NaN

In [80]:
data[data['title']=="Spider-Man 3"]['director_name']

4    Sam Raimi
Name: director_name, dtype: object

# Q8 - How many different movies have been directed by James Cameron between year 2005 to 2010?

In [81]:
directors

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [87]:
james_id=directors[directors['director_name']=='James Cameron']['id'][0]

In [88]:
james_id

np.int64(4762)

In [89]:
james_movies=movies.loc[(movies["director_id"] == james_id) & (movies["year"] >= 2005) & (movies["year"] <= 2010)]

In [90]:
james_movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday

In [91]:
#Let us write a function to do the exact same thing for whichever director we want.

In [92]:
def solve(director_name, start_year, end_year):
  director_id = directors[ directors['director_name'] == director_name].reset_index(drop = True)["id"][0]

  director_movies = movies[(movies["director_id"] == director_id)]

  df = director_movies[ (director_movies["year"] >= start_year) & (director_movies["year"] <= end_year) ]

  return df

In [93]:
solve("James Cameron", 2005, 2010)

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday

In [94]:
directors

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [95]:
solve("Christopher Nolan", 2005, 2010)

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
65,43662,185000000,187,1004558444,The Dark Knight,8.2,12002,4765,2008,Jul,Wednesday
96,43693,160000000,167,825532764,Inception,8.1,13752,4765,2010,Jul,Wednesday
119,43716,150000000,115,374218673,Batman Begins,7.5,7359,4765,2005,Jun,Friday
1196,44793,40000000,74,109676311,The Prestige,8.0,4391,4765,2006,Oct,Thursday

In [96]:
solve("Aadarsh Nolan", 2005, 2010)

KeyError: 0

In [97]:
def solve(director_name, start_year, end_year):
  director_id = directors[ directors['director_name'] == director_name].reset_index(drop = True)["id"]

  if len(director_id)!=0:
    director_id = directors[ directors['director_name'] == director_name].reset_index(drop = True)["id"][0]
    print(director_id)
    director_movies = movies[(movies["director_id"] == director_id)]

    df = director_movies[ (director_movies["year"] >= start_year) & (director_movies["year"] <= end_year) ]
    return df
  else:
    return "Not a Director Yet"

In [98]:
solve("Aadarsh Nolan", 2005, 2010)

'Not a Director Yet'

# Conclusion

In this business case study, I explored movie and director datasets using Python and Pandas to extract meaningful insights from the data.

Throughout this analysis, I learned and applied the following concepts:

--> Data Exploration: Examined datasets using head(), info(), and other basic methods.

--> Data Manipulation: Filtered records based on conditions and formatted release dates.

--> Data Aggregation: Used groupby(), value_counts(), and nunique() to analyze director gender distribution and count unique movies and directors.

--> Data Filtering: Identified movies released in specific years and directors who directed movies from 2010 onwards.

--> Data Merging: Combined movie and director datasets using merge() to retrieve information such as the director of Spider-Man 3.

Reusable Functions: Created a function to retrieve movies directed by a specified director within a given year range, including handling cases where the director is not found.

Overall, this case study helped me strengthen my practical understanding of Pandas and develop a structured approach to solving data analysis problems. 
These techniques can be applied to real-world business datasets to filter information, summarize data, identify patterns, and generate useful insights 
for decision-making.